name: xrviz

channels:
  - conda-forge

dependencies:
  - python=3.7
  - panel
  - holoviews
  - hvplot
  - xarray
  - netcdf4
  - datashader
  - metpy
  - geoviews>=1.9.1
  - dask
  - pip
  - pip:
    - git+https://github.com/intake/xrviz.git
