#!/bin/bash

# Install the dependencies
conda install -c conda-forge -y python=3.7 geoviews metpy xrviz --file ./requirements.txt

# Get rid of source code
rm -rf xrviz
rm -rf docs

# Get into examples
cd examples
